marshalutils.cpp: Fix error: no match for 'operator<<' (operand types are 'QDBusArgument' and 'const RouteStructure')
This appears with clang-11 and gcc 12:

Fixes: In file included from ../../recipe-sysroot/usr/include/QtDBus/QDBusMetaType:1,
                 from ../../git/libconnman-qt/marshalutils.cpp:34:
../../recipe-sysroot/usr/include/QtDBus/qdbusmetatype.h: In instantiation of 'QMetaType qDBusRegisterMetaType() [with T = RouteStructure]':
../../git/libconnman-qt/marshalutils.cpp:194:42:   required from here
../../recipe-sysroot/usr/include/QtDBus/qdbusmetatype.h:71:59: error: no match for 'operator<<' (operand types are 'QDBusArgument' and 'const RouteStructure')
   71 |     auto mf = [](QDBusArgument &arg, const void *t) { arg << *static_cast<const T *>(t); };
      |                                                       ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../recipe-sysroot/usr/include/QtDBus/qdbusmetatype.h:45,
                 from ../../recipe-sysroot/usr/include/QtDBus/QDBusMetaType:1,
                 from ../../git/libconnman-qt/marshalutils.cpp:34:
/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/honister-qt6/webos-ports/tmp-glibc/work/core2-64-webos-linux/libconnman-qt/1.2.35+gitAUTOINC+088350de01-r0/recipe-sysroot/usr/include/QtDBus/qdbusargument.h:87:20: note: candidate: 'QDBusArgument& QDBusArgument::operator<<(uchar)'
   87 |     QDBusArgument &operator<<(uchar arg);

Signed-off-by: Herman van Hazendonk <github.com@herrie.org>